services:

  # Service for building HTML
  sphinx:
    image: docker.io/nitrokey/sphinx
    container_name: sphinx_build
    working_dir: /docs/source  # Use source as the working directory
    volumes:
      - ./source:/docs/source
      - ./locales:/docs/source/locales
      - ./build:/docs/build
      - ./dist:/docs/dist

  # Service for running sphinx-build to extract gettext files
  gettext:
    image: docker.io/nitrokey/sphinx
    container_name: sphinx_gettext
    working_dir: /docs
    volumes:
      - ./locales:/docs/locales
      - ./source:/docs
      - ./build:/docs/build
      - ./source/conf.py:/docs/conf.py

  # Service for updating locales with sphinx-intl
  intl:
    image: docker.io/nitrokey/sphinx
    container_name: sphinx_intl
    working_dir: /docs
    volumes:
      - ./source/conf.py:/docs/conf.py
      - ./locales:/docs/locales
      - ./build:/docs/build
